version: "3.9"
services:
  api:
    build: ./infra/api
    ports:
      - 5173:5173
    volumes:
      - ./api:/api-data
  
  front:
    build: ./infra/front
    tty: true
    ports:
      - 3002:3000
    volumes:
      - ./front:/front-data
      - nestjs-node-modules:/front-data/node_modules

  web:
    image: nginx:1.20-alpine
    ports:
      - 8082:80
    volumes:
      - ./api:/api-data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /api-data

  db:
    build: ./infra/mysql
    ports:
      - 33002:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  nestjs-node-modules: